# Generated by Django 2.2.5 on 2019-09-14 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='entryrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('exit_time', models.DateTimeField(auto_now_add=True)),
                ('entry_time', models.DateTimeField(auto_now=True)),
                ('registration_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.studentsrecord')),
            ],
        ),
    ]
